### PR TITLE
Add Support for Ruby 3.2

### PR DESCRIPTION
**Pull request by nicolaa**
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

Addresses https://github.com/zipmark/rspec_api_documentation/issues/505

### CODE REVIEW

**Review by cickes — APPROVED** [review]
LGTM.  This is a beneficial update.  The project benefits greatly by pushing this one out.

Notably, the version number would need a new MAJOR version.
[Semantic versioning](https://semver.org/)

**Comment by schm** [comment]
@nicolaa Thanks for the contribution. I hope this gets merged eventually.

> Notably, the version number would need a new MAJOR version.

@cickes I don't think so. `File.exist?` is part of the core library since well before `2.0.0`. https://ruby-doc.org/core-1.8.6/File.html#method-c-exist-3F So this change is in no way backwards incompatible.

**Comment by bf4** [comment]
Looks like maybe https://github.com/stitchfix/rspec_api_documentation is the active fork to follow?

**Comment by santib** [comment]
@oestrich @jakehow what's the maintenance status of this gem? Are you looking for new maintainers? It'd be quite important to get this trivial PR merged 😬 

Thanks 🙌

**Comment by bf4** [comment]
We just upgraded to Ruby 3.3.0
We'll be building off the https://github.com/stitchfix/rspec_api_documentation fork for now but might start our own or transition to rspec-openapi and rswag like others have

**Comment by bf4** [comment]
Project needs to be adopted

**Comment by santib** [comment]
FWIW in https://github.com/rootstrap/rails_api_base we migrated to:
- [RSpec OpenAPI](https://github.com/exoego/rspec-openapi) for generating API documentation
- [RSwag](https://github.com/rswag/rswag) for serving the API documentation
More info in https://github.com/rootstrap/rails_api_base/blob/main/docs/api_documentation.md

**Comment by apotema** [comment]
These are some great libs @santib .  But it would be good to have this lib back.

**Comment by jakehow** [comment]
@vladveterok @bf4 lots of requests for maintenance and little volunteering to do it...  I don't think this PR  passed travisCI originally which is why it was not merged quickly. Travis now requires payment even on free plan which is probably why it's been removed.  I am not sure if there is an alternative these days for OSS CI builds that is still free.

Happy to add anyone who wants to push some of these items forward ... @bf4 ?

**Comment by bf4** [comment]
@jakehow Sure. I'll make a github actions test matrix pr on Wednesday if no one else has yet.  (I'm afk right now)

**Pull request merged**
