### PR TITLE
Fix #394 API Blueprint: Add api_explanation in template

### LINKED ISSUE #394: api_blueprint without api_explanation
Could you please add `{{ api_explanation }}` to `api_blueprint_index.mustache`?

```
FORMAT: A1
# {{ api_name }}

{{ api_explanation }} <-----------

{{# sections }}
```

And also update the gem? In the currente released version, it does not come with `# {{api_name}}`  :cry: 

https://github.com/zipmark/rspec_api_documentation/blob/35bac0b4718d7bfbd5b92c7b09b89ff1cbca17d3/templates/rspec_api_documentation/api_blueprint_index.mustache#L2

My Gemfile 

```
[...]
group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'rspec_api_documentation'
[...]
```

### PR DESCRIPTION
**Pull request by SrMouraSilva**

### CODE REVIEW

**Comment by marchi-martius** [comment]
👍

**Comment by entity1991** [comment]
👍

**Comment by marchi-martius** [comment]
@oestrich Hey!
Does it look good for you? Because it would be great to get the `api_explanation` in ApiBlueprint without forking/patching template. Please ping me if you need any help here.

**Comment by oestrich** [comment]
Thanks!

**Pull request merged**
