### PR TITLE
Update readme configuration file

### PR DESCRIPTION
**Pull request by maryshirl**
Setup the configuration under config/initializers/rspec_api_documentation.rb 
instead of spec/spec_helper.rb since the latter does't work.

### CODE REVIEW

**Comment by sadovnik** [comment]
Why are you sure it doesn't work? Could you show your `spec_helper.rb`?

**Comment by oestrich** [comment]
Yeah, this should definitely be set up in the `spec` folder. You don't want RAD loaded in production. Closing this PR, but happy to continue diagnosing why the issue came up here or in a new issue.

**Comment by maryshirl** [comment]
I was focused on making RAD work and I didn't think about that. Thanks @oestrich! 

@sadovnik, here's how my spec_helper.rb looks:

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  config.shared_context_metadata_behavior = :apply_to_host_groups
end

RspecApiDocumentation.configure do |config|
  config.api_name = 'THIS IS API Documentation'
end

and it's giving me the following error:
 undefined method `configure' for RspecApiDocumentation:Module

**Comment by maryshirl** [comment]
Hi @oestrich! Can you help me check why the rspec api documentation isn't working?

**Pull request closed without merging**
