### PR TITLE
Use SVG badges

### PR DESCRIPTION
**Pull request by tagliala**
[ci skip]

Before and after:
image

### CODE REVIEW

**Comment by ariejan** [comment]
@oestrich seems ok to me. Can I help out with handling issues / pull requests?

**Comment by oestrich** [comment]
I'm fine merging this, but is there a reason for svg vs what we have now? Since they look the same.

**Comment by tagliala** [comment]
Hi,

`.png` badges look different in both height, background-color and font weight

Maybe a screenshot with a retina display shows the differences better

(before -> after)

image

**Comment by oestrich** [comment]
Thanks!

**Pull request merged**
