### PR TITLE
Remove unneeded default values

### PR DESCRIPTION
**Pull request by aadityataparia**
closes https://github.com/zipmark/rspec_api_documentation/issues/419

Removes default values for not `required` fields.

### CODE REVIEW

**Comment by aadityataparia** [comment]
@zipmark Please 🙏

**Comment by aadityataparia** [comment]
@jakehow Please 🙏

**Comment by aadityataparia** [comment]
@oestrich Please 🙏

**Comment by oestrich** [comment]
@aadityataparia Can you update the PR to fix the merge conflict? I suspect it's just taking whatever master has now, but I want to have you check that.

**Comment by aadityataparia** [comment]
@oestrich Done ✅

**Pull request merged**
