### PR TITLE
Add clearer slate support in README. Reorganize slate_example.mustach…

### PR DESCRIPTION
**Pull request by E1337Kat**
…e for cleaner pages.

I also removed json as a language so that it would always show up (since it is used to describe request/response bodies, etc.)

### CODE REVIEW

**Comment by oestrich** [comment]
Thanks for the PR! Can you get travis passing? I think you just need to update the one slate feature file for the new output and it's good to go.

**Comment by E1337Kat** [comment]
ok! Sorry about that.

**Comment by E1337Kat** [comment]
Hmm, I can't seem to get it to work. I think the issue is that the curl output is not being... outputted. I need to investigate before my changes to make sure.

**Comment by E1337Kat** [comment]
Yay!

**Comment by oestrich** [comment]
Thanks again!

**Pull request merged**
