### PR TITLE
Test more recent versions of Ruby on Travis

### PR DESCRIPTION
**Pull request by davidstosik**
Added:
- 2.4.9 (reached end-of-life but may temporarily help in incremental debugging)
- 2.5.8
- 2.6.6

Did not add 2.7.x yet because it introduces *a lot* of warnings.

Did not remove any past version yet because until decided otherwise, they should be supported by the gem. (I would recommend a major version bump when those versions get dropped.)

The idea is that developments from now on should be future-proof, and changes should be tested on current versions of Ruby.

---

Note I had to relax WebMock's version because it introduced support for Ruby 2.4 in its version 2.3.1.

This **does not work** yet. There is one spec that used to pass with the older version of WebMock (in older versions of Ruby), but that does not pas anymore.
My guess is that it relied on some implementation detail of the WebMock gem, so I am working on finding out how to fix this.

(Additional note: I just noticed Cucumber runs only if RSpec succeeds. Running Cucumber locally, I noticed 4 scenarios fail, also potentially due to changes in WebMock.)

### CODE REVIEW

**Comment by davidstosik** [comment]
An additional note on WebMock. I updated it to the latest 2.x because Ruby 2.4 support was introduced in 2.3.1, but 3.x versions of WebMock introduce more changes that will require more adjustments on rspec_api_documentation's side.
Going with small iterations to make every step clear, understandable and safe to merge.

Updating to WebMock 2.x means that:

> require 'webmock' does not enable WebMock anymore. gem 'webmock' can now be safely added to a Gemfile and no http client libs will be modified when it's loaded. Call WebMock.enable! to enable WebMock.
>
> Please note that require 'webmock/rspec', require 'webmock/test_unit', require 'webmock/minitest' and require 'webmock/cucumber' still do enable WebMock.

Source: [WebMock's
CHANGELOG.md](https://github.com/bblimke/webmock/blob/master/CHANGELOG.md#200).

As rspec_api_documentation is very much tied to RSpec, I saw no problem with replacing all instances of `require 'webmock'` with `require 'webmock/rspec'`. Let me know if that was wrong. 🙏

**Comment by jakehow** [comment]
Agreed on approach to adding modern ruby support, and needing a major release in order to drop old rubies.

`require 'webmock/rspec'` also makes sense to me.

**Comment by davidstosik** [comment]
Thanks for the feedback! Now have to get in to work with Ruby 2.6.6...  👀

**Comment by davidstosik** [comment]
Note: WebMock 3.9.0 dropped support for Ruby 2.3 and 2.4 (in a minor version bump 🤔). I won't go further than 3.8.3 (if it can pass all the currently tested versions) in this PR.

**Comment by davidstosik** [comment]
Ready to go. :shipit: 🚀

**Comment by jakehow** [comment]
🙏

**Pull request merged**
