### PR TITLE
Added a resource explanation.

### PR DESCRIPTION
**Pull request by cpomerantz**
I added a way to put explanations on resources. The syntax is the same for explanations. I also modified the templates to put the explanation after the resource name. I felt like this helped to give more options for manual documentation.

### CODE REVIEW

**Comment by oestrich** [comment]
This looks good, but I would like some tests for the new feature before merging. Travis is also complaining about failing specs.

**Comment by cpomerantz** [comment]
Ok, I'll take a look and fix the issue with the broken tests. I'll also add some tests for the new code.

**Comment by jramos** [comment]
I've incorporated your changes into my fork and added tests.

https://github.com/jramos/rspec_api_documentation

**Comment by cpomerantz** [comment]
Thanks Justin, I meant to add tests for that but completely forgot.

**Comment by jeffutter** [comment]
@cpomerantz @jramos Any progress on this? I would love to see this in the main repo if possible.

**Comment by oestrich** [comment]
Closing due to age, if tests are pushed up make sure to mention me so I can look at this again.

**Pull request closed without merging**
