### PR TITLE
Exclude Gemfile.lock from version control

### PR DESCRIPTION
**Pull request by tagliala**
When developing a gem, use the gemspec method in your Gemfile to avoid
duplication. In general, a gem's Gemfile should contain the Rubygems
source and a single gemspec line. Do not check your Gemfile.lock into
version control, since it enforces precision that does not exist in the
gem command, which is used to install gems in practice. Even if the
precision could be enforced, you wouldn't want it, since it would
prevent people from using your library with versions of its dependencies
that are different from the ones you used to develop the gem.

Ref: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

### CODE REVIEW

**Comment by tagliala** [comment]
Tests are failing, but IMHO this is good chance of improving things.

If there is the need to test against specific gem versions, you could consider using [Appraisal](https://github.com/thoughtbot/appraisal) and restrict allowed dependency versions in `gemspec`. 

Btw, failures depend on:

- [ ] `rspec 3.5.0`
- [v] `capybara` 
- [v] `webmock`

I've pushed some more changes which fixes some failing specs, but I'm still not able to fix failures which depend on rspec 3.5.0.

**Comment by tagliala** [comment]
This rspec-core commit broke things https://github.com/rspec/rspec-core/commit/8e564dca9e5962bb6b41865af3fa49f2c3cbe5dd

**Comment by kurko** [comment]
Trade offs I see:

1. (this PR) to provide support to multiple versions of N dependencies, and therefore maintain a larger codebase and a multiplicity of possible new failure points, vs
2. maintain one set of dependencies with version ranges and ask developers to be within those ranges.

I think this PR is good, but the burden is on the maintainers later to support a combination of dependencies. I'm not sure it is worth it given the nature of the work (free, stressful). It would be a lot easier to distribute the weight with whoever uses this gem by asking them to update their own dependencies.

I totally agree on removing the `.lock` file, though.

**Comment by tagliala** [comment]
@kurko thanks for sharing your thoughts about this PR.

The main purpose of this PR is to make sure that tests pass against the dependencies specified in the `.gemspec` file.

Eg:

```
s.add_development_dependency "capybara", "~> 2.2"
```

Is not true, because to work with capybara 2.11 this change is needed: https://github.com/zipmark/rspec_api_documentation/pull/325/commits/eabc0a335b0aa9e8f4b929a7683c50e96f75e73a

**Comment by oestrich** [comment]
I spent a bit trying to get around the issue with rspec you noted. Something changed with how the examples work. There must be some configuration option we're missing as the `rspec-core` specs do the same thing we're doing and they pass.

**Comment by tagliala** [comment]
I gave another look and I also gave a look at the rspec-core specs but I'm still not able to fix this :\

**Comment by tagliala** [comment]
Hi,

I've rebased this gem and everything is green because of [this line](https://github.com/zipmark/rspec_api_documentation/pull/325/commits/4ed9259d1e734a651376e6c035265285a1d37a9f#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R6), which locks rspec to `~> 3.4.0` in Gemfile

Btw, you may be interested in cherry-picking:
- https://github.com/zipmark/rspec_api_documentation/pull/325/commits/2e4b4d38fc97308baab23bd6505a0e99ef803a71
- https://github.com/zipmark/rspec_api_documentation/pull/325/commits/532f23b45766e8fc1d98e23500b380a217e3889a
- https://github.com/zipmark/rspec_api_documentation/pull/325/commits/852fc96eb17845a7ebc38fd3321aa529068d1524
- https://github.com/zipmark/rspec_api_documentation/pull/325/commits/ab3d230c140a112ba56f9b9c51a161956fa8458a
- https://github.com/zipmark/rspec_api_documentation/pull/325/commits/cf2d9f681ef2bc6cf321f07749d5e3b4424ee89d

**Comment by tagliala** [comment]
for what is worth, testing with rspec 3.6.0 breaks a lot of specs

```
Finished in 0.55512 seconds (files took 1.71 seconds to load)
374 examples, 15 failures, 3 pending

Failed examples:

rspec ./spec/api_formatter_spec.rb:79 # Orders Updating an order
rspec ./spec/api_formatter_spec.rb:80 # Orders Viewing an order
rspec ./spec/example_spec.rb:67 # foobar foo
rspec ./lib/rspec_api_documentation/dsl.rb[1:1:1:1] # Posts /posts/:id{?option=:option} Single Post GET /posts/{id} Gets a post
rspec ./lib/rspec_api_documentation/dsl.rb[1:1:1:2] # Posts /posts/:id{?option=:option} Single Post GET /posts/{id} Returns an error
rspec ./lib/rspec_api_documentation/dsl.rb[1:2:1:1] # Posts /posts/:id Single Post DELETE /posts/:id Deletes a post
rspec ./lib/rspec_api_documentation/dsl.rb[1:3:1:1] # Posts /posts/:id Single Post PUT /posts/:id Updates a post
rspec ./lib/rspec_api_documentation/dsl.rb[1:4:1:1] # Posts /posts Posts Collection GET /posts Get all posts
rspec ./lib/rspec_api_documentation/dsl.rb[1:1:1:1] # Comments /comments Comments Collection GET /comments Get all comments
rspec ./lib/rspec_api_documentation/dsl.rb[1:1:1:1] # Posts /posts/:id{?option=:option} Single Post GET /posts/{id} Gets a post
rspec ./lib/rspec_api_documentation/dsl.rb[1:1:1:2] # Posts /posts/:id{?option=:option} Single Post GET /posts/{id} Returns an error
rspec ./lib/rspec_api_documentation/dsl.rb[1:2:1:1] # Posts /posts/:id Single Post DELETE /posts/:id Deletes a post
rspec ./lib/rspec_api_documentation/dsl.rb[1:3:1:1] # Posts /posts/:id Single Post PUT /posts/:id Updates a post
rspec ./lib/rspec_api_documentation/dsl.rb[1:4:1:1] # Posts /posts Posts Collection GET /posts Get all posts
rspec ./lib/rspec_api_documentation/dsl.rb[1:1:1:1] # Comments /comments Comments Collection GET /comments Get all comments

374 examples, 15 failures, 3 pending
```

Cucumber features are fine instead
```
63 scenarios (63 passed)
319 steps (319 passed)
```

**Comment by tagliala** [comment]
@oestrich there is an issue with the current master branch.

Try to run:

```
$ rspec spec/api_formatter_spec.rb:47 --format documentation
Run options: include {:locations=>{"./spec/api_formatter_spec.rb"=>[47]}}
```

you should see two failing specs
```
RspecApiDocumentation::ApiFormatter
  output
    with passing examples
      should list the generated docs (FAILED - 1)
    with failing examples
      should indicate failures (FAILED - 2)
```

The issue is due to `include FakeFS::SpecHelpers` which should be included in the container block

```
 $ rspec spec/api_formatter_spec.rb:47 --format documentation
Run options: include {:locations=>{"./spec/api_formatter_spec.rb"=>[47]}}

RspecApiDocumentation::ApiFormatter
  output
    with passing examples
      should list the generated docs
    with failing examples
      should indicate failures
```

**Comment by tagliala** [comment]
[Sandboxing](https://github.com/rspec/rspec-core/blob/master/spec/support/sandboxing.rb) should be the key

**Comment by tagliala** [comment]
Everything is green ✌️ 

All development specs are up to date, 15 separate commits so you could cherry-pick whatever you need

**Comment by sadovnik** [comment]
@tagliala seems like there are some conflicts appeared since last commit.

**Comment by tagliala** [comment]
@sadovnik

Hi, I'm not using this gem anymore but I will try to rebase on the current master and push force, if it is helpful to others and doesn't take too much time on my side

**Comment by sadovnik** [comment]
@tagliala what solution did you choose instead of this gem if not secret? : )

**Comment by tagliala** [comment]
I'm still separating docs and specs. I'm using the ol' good [Swagger](https://swagger.io/)

**Comment by oestrich** [comment]
Closing due to age.

**Pull request closed without merging**
