### PR TITLE
Cleans out ASCII_8BIT encoded response bodies

### PR DESCRIPTION
**Pull request by Ruxton**
We have an end point that returns an MP3 for streaming, this allows you to document endpoints that return such binary files.

### CODE REVIEW

**Comment by oestrich** [comment]
Looks good, can you include a test though?

**Comment by codebender** [comment]
+1

**Comment by jramos** [comment]
Feel free to add this PR to my fork.

https://github.com/jramos/rspec_api_documentation

**Comment by oestrich** [comment]
@Ruxton can you check to see that 8e670ea works for you?

**Pull request closed without merging**
